name: dash_chat_2
description: Windows 64-bit Optimized Chat UI
version: 0.0.18+win64  # 增加平台标识
homepage: https://github.com/asdfghj1397/Dash-Chat-2

environment:
  sdk: ">=3.0.0 <4.0.0"  # 升级 Dart SDK 要求
  flutter: ">=3.22.0"     # 强制 Flutter 3.22+ (Windows 11 兼容)

dependencies:
  # ===== Windows 核心依赖 =====
  flutter:
    sdk: flutter
  win32: ^5.0.0  # Windows API 集成
  window_management: 
    git: 
      url: https://github.com/flutter/packages
      path: packages/window_management/windows/
      ref: main

  # ===== 跨仓库 UI 组件 =====
  dash_chat_ui_kit:
    git:
      url: https://github.com/SebastienBtr/Dash-Chat-UI
      path: windows_ui/
      ref: win64-stable

  # ===== Windows 优化版依赖 =====
  directx_texture_loader: ^0.2.1
  win_video_player: ^1.3.0
  windows_taskbar: ^2.0.3  # 任务栏交互增强

dev_dependencies:
  windows_analytics: ^1.1.0  # Windows 专用调试工具
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/win/
    - assets/fonts/windows/
    - assets/win_styles/

  # ===== Windows 构建专属配置 =====
  windows:
    target_platform: x64
    icon: assets/icons/win/app_icon.ico  # 必须 .ico 格式
    dependencies:
      - win32
      - windows_taskbar
    build_args:
      - --enable-directx12
      - --disable-ios-compatibility
