name: dash_chat_2
description: Windows 64-bit Optimized Chat UI
version: 0.0.18+win64 # 平台标识
homepage: https://github.com/asdfghj1397/Dash-Chat-2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.0.0
  window_management:
    git:
      url: https://github.com/asdfghj1397/packages
      path: packages/window_management
      ref: main
  dash_chat_ui_kit: # 已切换到你提供的仓库
    git:
      url: https://github.com/asdfghj1397/Dash-Chat-2
      path: windows_ui/ # 假设你的代码在仓库的 windows_ui 子目录
      ref: win64-stable # 根据你的实际分支/tag调整
  directx_texture_loader: ^0.2.1
  win_video_player: ^1.3.0
  windows_taskbar: ^2.0.3

dev_dependencies:
  windows_analytics: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/win/
    - assets/fonts/windows/
    - assets/win_styles/
  windows:
    target_platform: x64
    icon: assets/icons/win/app_icon.ico
    dependencies:
      - win32
      - windows_taskbar
    build_args:
      - --enable-directx12
      - --disable-ios-compatibility
