name: dash_chat
description: Cross-platform Chat UI with Adaptive Design
version: 0.0.19 # 通用版本号
homepage: https://github.com/asdfghj1397/Dash-Chat-2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 跨平台基础依赖
  universal_io: ^2.0.4    # 替代部分平台特定IO操作
  provider: ^6.0.5        # 状态管理
  cached_network_image: ^3.2.3 # 图片加载
  
  # 平台自适应依赖
  platform: ^3.1.0        # 平台检测
  adaptive_components:   # 条件化组件
    git:
      url: https://github.com/asdfghj1397/adaptive_components
      ref: main

  # Windows 特定依赖（条件化）
  win32:
    hosted: 
      name: win32
      version: ^5.0.0
    on: windows
  
  # macOS 特定依赖
  macos_ui: ^0.4.0
    on: macos

  # Web 支持
  flutter_web_plugins:
    sdk: flutter
    on: web

dev_dependencies:
  # 跨平台测试框架
  integration_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/styles/
  
  # 多平台配置
  platforms:
    android:
      package: com.example.dash_chat
      icon: assets/icons/android/app_icon.png
    ios:
      bundleIdentifier: com.example.dashChat
      icon: assets/icons/ios/AppIcon.appiconset
    web:
      renderer: canvaskit
    windows:
      target_platform: x64
      dependencies:
        - win32
      build_args:
        - --enable-directx12
    macos:
      minimumOsVersion: '10.15'
