name: Build & Deploy (v4)

on:
  workflow_dispatch:  # 手动触发配置
    inputs:
      environment:
        description: '目标环境 (stage/prod)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod
      confirm-deploy:
        description: '确认部署操作 (true/false)'
        required: true
        default: true  # 修正：boolean 值不需要引号
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'flutter/pubspec.yaml'

env:
  REGISTRY_URL: ghcr.io/asdfghj1397/rustdesk2
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'stage' }}  # 修正：移动到 job 级别
    permissions:
      contents: read
      packages: write

    steps:
    # --- 代码检出与 Flutter 构建 ---
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'flutter'  # 必须指定检出路径

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.5

    - name: Build Flutter
      working-directory: ./flutter  # 确保与检出路径一致
      run: |
        flutter pub get
        flutter build apk --release

    # --- Docker 镜像构建 ---
    - name: Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: ./flutter  # 关键修正：上下文指向 Flutter 目录
        push: true
        tags: ${{ env.REGISTRY_URL }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --- Kubernetes 部署 ---
    - name: Set Kubernetes Context (v4)
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_SECRET }}
        context: ${{ inputs.environment }}-cluster
        cluster-type: generic
        set-current-context: true
        override: true

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v4
      if: ${{ inputs.confirm-deploy }}  # 修正：直接使用 boolean 值
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          ${{ env.REGISTRY_URL }}:${{ env.IMAGE_TAG }}
        namespace: ${{ inputs.environment }}-ns
        strategy: canary

    # --- 部署验证 ---
    - name: Verify Deployment
      run: |
        kubectl get pods -n ${{ inputs.environment }}-ns
        kubectl get svc -n ${{ inputs.environment }}-ns
