name: 1CI

env:
  # 注释符号后添加空格
  MIN_SUPPORTED_RUST_VERSION: "1.46.0"
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  # vcpkg version: 2024.06.15
  VCPKG_COMMIT_ID: "f7423ee180c4b7f40d43402c2feb3859161ef625"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  ensure_cargo_fmt:
    name: Ensure 'cargo fmt' has been run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rustfmt
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check

  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # 修正所有矩阵条目
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
          - { target: arm-unknown-linux-gnueabihf, os: ubuntu-20.04, use-cross: true }
          - { target: arm-unknown-linux-musleabihf, os: ubuntu-20.04, use-cross: true }
          - { target: i686-pc-windows-msvc, os: windows-2022 }
          - { target: i686-unknown-linux-gnu, os: ubuntu-20.04 }
