name: Flutter Build & Deploy (Final)

on:
  workflow_dispatch:  # 手动触发
    inputs:
      environment:
        description: 'Environment (stage/prod)'
        required: true
        default: 'stage'
        type: choice
        options: [stage, prod]
      confirm:
        description: 'Confirm deployment'
        required: true
        default: true
        type: boolean
  push:
    branches: [main]
    paths: ['flutter/pubspec.yaml']

env:
  FLUTTER_DIR: './flutter'  # 统一目录变量
  REGISTRY: ghcr.io/asdfghj1397/rustdesk2
  TAG: ${{ github.sha }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'stage' }}
    permissions:
      contents: read
      packages: write

    steps:
      # --- 代码检出 ---
      - name: Checkout code (subdir)
        uses: actions/checkout@v4
        with:
          path: ${{ env.FLUTTER_DIR }}  # 强制检出到子目录

      # --- Flutter 环境配置 ---
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.5'  # 必须加引号
          working-directory: ${{ env.FLUTTER_DIR }}

      - name: Disable analytics
        working-directory: ${{ env.FLUTTER_DIR }}
        run: flutter config --no-analytics

      # --- 构建验证 ---
      - name: Build preparation
        working-directory: ${{ env.FLUTTER_DIR }}
        run: |
          echo "当前Flutter版本: $(flutter --version)"
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.FLUTTER_DIR }}
        run: flutter build apk --release

      # --- Docker 镜像构建 ---
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.FLUTTER_DIR }}  # 关键路径修正
          push: ${{ inputs.confirm }}
          tags: ${{ env.REGISTRY }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Kubernetes 部署 ---
      - name: Setup Kubeconfig
        if: ${{ inputs.confirm }}
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_SECRET }}
          context: ${{ inputs.environment }}-cluster

      - name: Deploy manifests
        if: ${{ inputs.confirm }}
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ${{ env.FLUTTER_DIR }}/
