name: CI/CD Pipeline

# ================== 触发条件配置 ==================
on:
  # 1. 手动触发（GitHub 网页界面或 API）
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境 (prod/stage)'
        required: true
        default: 'stage'
      force:
        description: '强制跳过测试'
        required: false
        type: boolean

  # 2. 代码推送触发
  push:
    branches:
      - main
      - dev
    paths-ignore:  # 忽略文档类变更
      - 'docs/**'
      - 'README.md'

  # 3. PR 合并触发
  pull_request:
    types: [closed]
    branches:
      - main

# ================== 手动触发增强配置 ==================
jobs:
  manual-deploy:
    name: Manual Deployment
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Validate Inputs
        run: |
          echo "部署环境: ${{ github.event.inputs.environment }}"
          echo "强制模式: ${{ github.event.inputs.force || 'false' }}"
          
          # 输入校验逻辑
          if [ "${{ github.event.inputs.environment }}" != "prod" ] && [ "${{ github.event.inputs.environment }}" != "stage" ]; then
            echo "::error::环境参数必须是 prod 或 stage"
            exit 1
          fi

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          action: deploy
          manifests: ${{ format('./k8s/{0}/', github.event.inputs.environment) }}
          images: |
            my-registry/app:${{ github.sha }}

  # ================== 自动化流水线 ==================
  auto-build:
    name: Auto Build
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    needs: [manual-deploy]
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
